config/routes.rb
Rails.application.routes.draw do
  resources :submissions
  devise_for :users

  get 'game', to: 'submissions#gameIndex'
  root to: 'users#home'
  get 'search_round', to: 'submissions#search'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/submission.rb
class Submission < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :submissions
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_user!

end

app/controllers/submissions_controller.rb
class SubmissionsController < ApplicationController
  before_action :set_submission, only: [:show, :edit, :update, :destroy]

  # GET /submissions
  # GET /submissions.json
  def index
    @submissions = Submission.all
  end

  def search
      @submissions = Submission.where("round is ? ", params[:search_param])
      @users = User.all
  end

  # GET /submissions/1
  # GET /submissions/1.json
  def show
  end

  # GET /submissions/new
  def new
    @submission = Submission.new
  end

  # GET /submissions/1/edit
  def edit
  end

  # POST /submissions
  # POST /submissions.json
  def create
    @submission = Submission.new(submission_params)
    @submission.user = current_user
    respond_to do |format|
      if @submission.save
        format.html { redirect_to root_path notice: 'Submission was successfully created.' }
        format.json { render :show, status: :created, location: @submission }
      else
        format.html { render :new }
        format.json { render json: @submission.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /submissions/1
  # PATCH/PUT /submissions/1.json
  def update
    respond_to do |format|
      if @submission.update(submission_params)
        format.html { redirect_to @submission, notice: 'Submission was successfully updated.' }
        format.json { render :show, status: :ok, location: @submission }
      else
        format.html { render :edit }
        format.json { render json: @submission.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /submissions/1
  # DELETE /submissions/1.json
  def destroy
    @submission.destroy
    respond_to do |format|
      format.html { redirect_to submissions_url, notice: 'Submission was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def resetGame
    Submissions.delete_all
    redirect_to root_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_submission
      @submission = Submission.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def submission_params
      params.require(:submission).permit(:user_id, :round, :submission)
    end
end

app/controllers/user/registrations_controller.rb
class User::RegistrationsController < Devise::RegistrationsController
  before_action :configure_permitted_parameters

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:admin, :player])
    devise_parameter_sanitizer.permit(:account_update, keys: [:admin, :player])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def home
    @users = User.all
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/submissions_helper.rb
module SubmissionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_navigation.html.erb
<div class="navbar navbar-default navbar-static-top">
  <div class="container">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to "Things Game", root_path, class: "navbar-brand" %>
    <div class="navbar-collapse collapse navbar-responsive-collapse">
      <ul class="nav navbar-nav">
        <% if user_signed_in? %>
          <li><%= link_to "My Profile", edit_user_registration_path %></li>
          <li><%= link_to 'Logout', destroy_user_session_path, method: :delete%></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "ThingsProject" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>


    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <%= render 'layouts/navigation' %>

    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>

      <footer>
        <p>&copy; Tschudin Enterprises 2020</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/submissions/_form.html.erb
<%= form_for(@submission) do |f| %>

  <div class="form-group">
    <%= f.label :round %>
    <%= f.text_field :round, autofocus: true, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :submission %>
    <%= f.text_area :submission, autofocus: true, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/submissions/_lookup.html.erb
<%= form_tag search_round_path, remote: true, method: :get, id: "submission-round-form" do %>
  <%= text_field_tag :search_param, params[:search_param] %>
  <%= button_tag(type: :submit, class: "btn btn-lg btn-success") do %>
           <i class="fa fa-search"></i> "Guessing Round"
         <% end %>
<% end %>

app/views/submissions/_result.html.erb
<div id="round-search-results">
  <div class="row">
    <% @submissions.each do |submission| %>
        <div class="well col-md-4">
          <p><%= submission.submission %></p>
          <input type="checkbox">Done
          <input type="text">

        </div>
    <% end %>
  </div>
</div>

app/views/submissions/_result.js.erb
$('#results').html("<%= j (render 'submissions/result.html') %>")

app/views/submissions/edit.html.erb
<h1>Editing Submission</h1>

<%= render 'form', submission: @submission %>

<%= link_to 'Show', @submission %> |
<%= link_to 'Back', submissions_path %>

app/views/submissions/gameIndex.html.erb
<p id="notice"><%= notice %></p>

<h1>Submissions</h1>

<ul class="listing">
  <div class="row">
    <% @submissions.each do |submission| %>
        <div class="well col-md-4">
          <p><%= submission.submission %></p>
        </div>
    <% end %>
  </div>
</ul>
<%= link_to 'Next Round', root_path, class: "btn btn-success" %>

app/views/submissions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Submissions</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>User</th>
      <th>Round</th>
      <th>Submission</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @submissions.each do |submission| %>
      <tr>
        <td><%= submission.user.email %></td>
        <td><%= submission.round %></td>
        <td><%= submission.submission %></td>
        <td><%= link_to 'Show', submission %></td>
        <td><%= link_to 'Edit', edit_submission_path(submission) %></td>
        <td><%= link_to 'Destroy', submission, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Submission', new_submission_path %>

app/views/submissions/new.html.erb
<h1>New Submission</h1>

<%= render 'form', submission: @submission %>

<%= link_to 'Back', root_path %>

app/views/submissions/search.html.erb
<p id="notice"><%= notice %></p>

<h1>Things</h1>

<div id="results">
  <%= render 'result' %>
</div>

<%= link_to 'Next Round', root_path, class: "btn btn-success" %>

app/views/submissions/show.html.erb
<p id="notice"><%= notice %></p>




<%= link_to 'Edit', edit_submission_path(@submission) %> |
<%= link_to 'Back', submissions_path %>

app/views/users/home.html.erb
<p id="notice"><%= notice %></p>

<h1>Things Game</h1>

<%= link_to "Add a Thing", new_submission_path, class: "btn btn-success" %>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Users</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.usernames %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= form_tag search_round_path, method: :get, id: "submission-round-form" do %>
  <%= text_field_tag :search_param, params[:search_param] %>
  <%= button_tag "Guessing Round", class: "btn btn-success" %>
<% end %>